add_newline = false
palette = "catppuccin_mocha"
command_timeout = 1000

format = """$directory$character"""
right_format = """$git_branch$git_status$cmd_duration$nodejs$python$golang$rust$java"""

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'
vicmd_symbol = '[N](bold mauve)'

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold lavender"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = '[$symbol$branch]($style) '
symbol = " "
style = "bold mauve"

[git_commit]
disabled = false
commit_hash_length = 1

[git_state]
disabled = false

[git_status]
ignore_submodules = true
format = '([+$staged](bold green))([ !$modified](bold yellow))([ ?$untracked](bold blue))([ ✘$deleted](bold red))([ ⇡$ahead_count](bold teal))([ ⇣$behind_count](bold peach)) '
staged = "$count"
modified = "$count"
untracked = "$count"
deleted = "$count"
ahead = "$count"
behind = "$count"

[cmd_duration]
min_time = 2_000
format = '[$duration](bold yellow) '

[nodejs]
format = '[$symbol($version)]($style) '
symbol = " "
style = "bold green"

[python]
format = '[$symbol($version)]($style) '
symbol = " "
style = "bold yellow"

[golang]
format = '[$symbol($version)]($style) '
symbol = " "
style = "bold cyan"

[rust]
format = '[$symbol($version)]($style) '
symbol = " "
style = "bold peach"

[java]
format = '[$symbol($version)]($style) '
symbol = " "
style = "bold red"

[aws]
disabled = true

[kubernetes]
disabled = true

[docker_context]
disabled = true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
