# Splits
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Windows
bind c new-window -c "#{pane_current_path}"
bind r command-prompt "rename-window %%"
bind H previous-window
bind L next-window
bind w list-windows
bind ^ last-window

# Panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind z resize-pane -Z
bind x kill-pane
bind K send-keys "clear" \; send-keys "Enter"

# Resize panes
bind -r Left  resize-pane -L 5
bind -r Right resize-pane -R 5
bind -r Down  resize-pane -D 5
bind -r Up    resize-pane -U 5

# Sessions
bind S choose-session
bind d detach
bind R source-file ~/.config/tmux/tmux.conf \; display "Config reloaded"

# Misc
bind : command-prompt
bind * setw synchronize-panes

# Copy mode (vi)
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
